#:kivy 1.8.0

<MainWindow>:
	BoxLayout:
		center_x: root.width / 2
		orientation: 'vertical'
		padding: [0,20]
		spacing: 100 
		
		Label:
			font_size: 70
			text: root.informationToShow

		Label:
			font_size: 70
			text: root.timeLeft

		Button:
			id: startButton
			text: 'Start'
			on_release: root.start()
		
		Button:
			id: stopButton
			text: 'Stop'
			on_release: root.stop()

		Button:
			id: workRest
			on_release: root.changeFormat()
			text: root.currentFormat